language: r
dist: bionic
sudo: required
cache: packages
addons:
  apt:
    update: true
    packages:
      - python3
      - python3-pip 
      - python3-all-dev
      - python3-setuptools
      - python3-wheel
      - python3-venv
      - build-essential
      - zlib1g-dev
      - cmake
      - r-base-core
      - r-base-dev
      - liblapack-dev
install:
  - sudo R -e -q 'install.packages("keras", repos = "http://cran.rstudio.com/")'
  - R -e -q 'keras::install_keras()'
