language: r
dist: bionic
sudo: required
cache: 
  - packages
  - r_packages

addons:
  apt:
    update: true
    packages:
      - python3
      - python3-pip 
      - python3-all-dev
      - python3-setuptools
      - python3-wheel
      - python3-venv
      - build-essential
      - zlib1g-dev
      - cmake
      - r-base-core
      - r-base-dev
      - liblapack-dev
      
r_packages:
  - checkmate
  - data.table
  - logging
  - ggplot2
  - openssl
  - abind
  - foreach
  
install:
  - sudo R -q -e 'install.packages("keras", repos = "http://cran.rstudio.com/")'
  - R CMD INSTALL .
