language: r
dist: bionic
sudo: false

cache: 
  packages: TRUE
  ccache: TRUE
  directories:
    - $HOME/.keras
    - $HOME/.cache/pip

addons:
  apt:
    update: true
    packages:
      - ccache
      
before_install:
  - mkdir $HOME/.R && echo -e 'CXX_STD = CXX14\n\nVER=\nCCACHE=ccache\nCC=$(CCACHE) gcc$(VER) -std=gnu99\nCXX=$(CCACHE) g++$(VER)\nC11=$(CCACHE) g++$(VER)\nC14=$(CCACHE) g++$(VER)\nFC=$(CCACHE) gfortran$(VER)\nF77=$(CCACHE) gfortran$(VER)' > $HOME/.R/Makevars
  
install:
  - apt-get update
  - apt-get install python3
  - python3 -m pip install --upgrade --ignore-installed --user travis virtualenv gym gym[atari]
  - R -q -e 'install.packages(c("keras", "checkmate", "data.table", "logging", "ggplot2", "openssl", "abind", "foreach", "knitr", "rmarkdown"), repos = "http://cran.rstudio.com/")'
  - R -e 'keras::install_keras()'
  - R -e 'tensorflow::tf_config()'
  - R CMD INSTALL .
