language: r
dist: bionic
sudo: required
cache: 
  - packages
  - ccache

addons:
  apt:
    update: true
    packages:
      - ccache
      - python3
      - python3-pip 
      - python3-all-dev
      - python3-setuptools
      - python3-wheel
      - python3-venv
      - build-essential
      - zlib1g-dev
      - cmake
      - r-base-core
      - r-base-dev
      - liblapack-dev  
      
before_install:
  - mkdir $HOME/.R && echo -e 'CXX_STD = CXX14\n\nVER=\nCCACHE=ccache\nCC=$(CCACHE) gcc$(VER) -std=gnu99\nCXX=$(CCACHE) g++$(VER)\nC11=$(CCACHE) g++$(VER)\nC14=$(CCACHE) g++$(VER)\nFC=$(CCACHE) gfortran$(VER)\nF77=$(CCACHE) gfortran$(VER)' > $HOME/.R/Makevars
  
install:
  - sudo R -q -e 'install.packages(c("keras", "checkmate", "data.table", "logging", "ggplot2", "openssl", "abind", "foreach"), repos = "http://cran.rstudio.com/")'
  - R CMD INSTALL .
