language: r
sudo: required
cache: packages
addons:
  apt:
    update: true
    packages:
      - python3
      - python3-pip 
      - python3-dev 
      - build-essential
      - zlib1g-dev
before_install:
  - sudo apt-get update
  - sudo apt-get install python3
  - sudo apt-get install -y software-properties-common
  - sudo add-apt-repository -y ppa:george-edison55/cmake-3.x
  - sudo apt-get update
  - sudo apt-get install -y cmake
  - sudo apt-get install -y zlib1g-dev
  - sudo pip3 install cmake
  - sudo pip3 install tensorflow
  - sudo pip3 install keras
  - sudo pip3 install gym
  - sudo pip3 install gym[atari]
env:
  matrix:
  - _R_CHECK_LENGTH_1_CONDITION_=true
r:
  - devel
  - release
r_packages:
  - devtools
  - covr
r_github_packages:
  - codecov/example-r
  - hadley/pkgdown
  - rstudio/keras
before_script:
  - R --no-save <<< 'library("devtools"); document()'
  - R --no-save <<< 'library("tensorflow"); install_tensorflow()'
  - R --no-save <<< 'library("keras"); install_keras()'
after_success:
  - Rscript -e 'covr::codecov()'
  - Rscript -e "covr::coveralls()"
  - 'if [[ "$TRAVIS_PULL_REQUEST" == "false" && "$TRAVIS_BRANCH" == "master" && "$TRAVIS_R_VERSION_STRING" == "release" && "$TRAVIS_EVENT_TYPE" != "cron" ]] ; then
    R --no-save <<< "devtools::install(); pkgdown::build_site()";
    git checkout master;
    export TRAVIS_COMMIT_MSG="$(git log --format=%B --no-merges -n 1)";
    git config --global user.name "Travis CI";
    git config --global user.email "$COMMIT_AUTHOR_EMAIL";
    git config credential.helper "store --file=.git/credentials";
    echo "https://${GH_TOKEN}:@github.com" >> .git/credentials;
    git config push.default matching;
    git add --force man/*;
    git add --force README.md;
    git add --force docs/*;
    git rm -r --cached $(find . -type d -name "*_cache");
    git commit man DESCRIPTION NAMESPACE README.md docs -m "update auto-generated documentation [ci skip]" -m "$TRAVIS_COMMIT_MSG" || true;
    git push;
  fi;'
  - 'if [[ "$TRAVIS_R_VERSION_STRING" == "devel" && "$TRAVIS_EVENT_TYPE" != "cron" ]] ; then
    Rscript -e "covr::coveralls()";
  fi;'
